# print(len("jenny khatri"))
# length=len("Santanu Paikaray")
# print("Your name has " +str(length) + " characters")
first_number=input("Enter First Number: ")
second_number=input("Enter Second Number: ")
sum=int(first_number) + int(second_number)
print(sum)